### ISSUE TITLE
a better solution

### ISSUE THREAD

**Issue by watano** [Avocarrot/json2view#18]
json2view is very good idea, i read  u codes, find a better solution, we can discuss it. 
1. use a static web server for remote loading json;
2. build a helper class for setContent(),it can load json by http.And it very like the android setContent(), u can simply use reg replace tools to replace u codes to toogle production env or test env.
3. json convert can put into setContent() helper class. it read xml from http and convert it to json. BTW,I read u codes,i think that u json is very simply format, it very like xml. so u can remove the convert, directly use xml for dynamic view.

**Comment by watano** [comment]
sry, it's not the setContent(),it's inflater.inflate.

**Comment by JY0284** [comment]
Directly using XML is not an efficient way. Android use aapt to convert plain XML to binary for efficiency,  parse plain XML will be slow.
