### ISSUE TITLE
Scroll View Support

### ISSUE THREAD

**Issue by sampathevive** [Avocarrot/json2view#22]
I have a question regarding the scroll view support in this jar. I tried putting the scrollview in the json file and tried to get the view. It says java.lang.ClassNotFoundException: android.widget.ScrollView$LayoutParams.
I have even tried putting a scrollview inside a RelativeLayout which was also failing.
Can you please help me in this?

**Comment by giorgosera** [comment]
+1

**Comment by sampathevive** [comment]
Thank you . :+1:
