### ISSUE TITLE
iOS support :) 

### ISSUE THREAD

**Issue by jaumard** [Avocarrot/json2view#24]
Hi, 

Just found your project ! And for a project I need to support web, Android and iOS interface from JSON.
It would be cool if your project support also iOS interface (or a common interface for both).

Anyway thanks for this great job !

**Comment by giorgosera** [comment]
Thanks for the suggestion @jaumard . We are actually working on an iOS implementation at the moment. We don't have any timeline for release yet but stay tuned :)

**Comment by jaumard** [comment]
Cool !! I think with the new constraint layout in Android there some things to do to have something common between the two OS ;) exiting ^^

**Comment by eestein** [comment]
@giorgosera hey man, any news on that? I'd love to use this lib, but I also need it for iOS.

Amazing job, thanks!

**Comment by giorgosera** [comment]
Hey @eestein . Unfortunately, no plans to have this for iOS atm. Apologies for the inconvenience.
