### ISSUE TITLE
Multi button demo

### ISSUE THREAD

**Issue by walter16** [Avocarrot/json2view#27]
Can you provide a multi button response routines such as Button1/2/3, Textview1/2/3, Imageview1/2/3, a total of 9 widget.Button1 in response to modify the Textview1/2/3 and Imageview1/2/3 show or not? the Button2 response to modify the Textview1/2/3's Text content.Button3 response to switch Imageview1/2/3 display pictures (assuming 3). thank you very much!

**Comment by tsiougkosn** [comment]
Hi there,

With the json2view you can create the layout with your TextView, ImageView and Buttons.
Then in your code you need to implement the logic to update every ui component on button event.

**Comment by walter16** [comment]
I am revising. the json2view  is very good, it is what I need. Thank you!
