### ISSUE TITLE
can't get id for child layouts

### ISSUE THREAD

**Issue by Manju96** [Avocarrot/json2view#34]
How can I get the id for child layouts and their view and can i use the existing id with the dynamicview created with json2view.??
And instead of overriding or adding a view can i change the existing views??

**Comment by tsiougkosn** [comment]
Hey there,

You can check the example 02
(https://github.com/Avocarrot/json2view/wiki/Creating-Dynamic-Layouts)
and you can get the view that you define in your `SampleViewHolder`

Let me know if that help you,
Nikos
