### ISSUE TITLE
Can't get object IDs

### ISSUE THREAD

**Issue by MkVII** [Avocarrot/json2view#36]
Hi, thanks for this tool.

When I create a checkbox for example using this tool, I cannot set the resource ID which I need to initialize the checkbox.

Thanks
Brad

**Comment by tsiougkosn** [comment]
Hello Brad,

You can check the example 02
(https://github.com/Avocarrot/json2view/wiki/Creating-Dynamic-Layouts)
In your case you will have a CheckBox instead of the clickableView so you can have reference to your Checkbox by using 
```
((SampleViewHolder) sampleView.getTag()).checkbox....
```

Let me know if that help you,
Nikos
