### ISSUE TITLE
多语言下的适配

### ISSUE THREAD

**Issue by zhangbohui10** [Avocarrot/json2view#37]
在土耳其语情况下，I和i是无法通过toUpperCase()和toLowerCase()正常转换的，代码中使用的都是默认的，应该去规定转换目标，例如：**toLowerCase(Locale.ENGLISH)**   **toUpperCase(Locale.ENGLISH)**

**Comment by tsiougkosn** [comment]
Hey there,

I don't understand what is the problem, and google translate doesn't help me to understand it .
Could you explain your question/issue in english ?

Best,
Nikos
