### ISSUE TITLE
Get data from editText

### ISSUE THREAD

**Issue by NamitaWani** [Avocarrot/json2view#38]
How to get data from edit text on Click of button, if EditText and button is passed from JSON.

And also is there any way to add DynamicId in SampleViewHolder dynamically rather than hardcoding it.

**Comment by tsiougkosn** [comment]
Hey there,

For your 1st question, you need to set the EditText In your ViewHolder, and as you have the reference in the EditText get the entered data.

You can't set the DynamicId dynamically, but if you like you can update the library to do that.

Best,
Nikos
