### ISSUE TITLE
textSize in Wiki

### ISSUE THREAD

**Issue by rahulketch** [Avocarrot/json2view#40]
Hi,
The page on Available Properties seems to have the type field of textSize incorrectly specified. I think it should be dimen instead of textSize.

**Comment by tsiougkosn** [comment]
Hello @rahulketch 
Can you send exactly what is not correctly specified ?
Please send the file/line that have the issue and your suggestion.
Nikos

**Comment by rahulketch** [comment]
Hi! The issue in the wiki and not in the library itself. At https://github.com/Avocarrot/json2view/wiki/Available-Properties
The example under textSize should be {"name":"textSize", "type":"dimen", "value":"13sp"} instead of {"name":"textSize", "type":"textSize", "value":"13sp"}

**Comment by tsiougkosn** [comment]
Ok! You are right. Thanks for reporting that.
