### ISSUE TITLE
iOS version needed?

### ISSUE THREAD

**Issue by kintaro1981** [Avocarrot/json2view#41]
is a json2view iOS version needed or iOS doesn't need it?

**Comment by mars009** [comment]
I would love to see something like this. I looked around, but I did not find anything for iOS that does what json2view does for android.

**Comment by tsiougkosn** [comment]
Hey,
There isn't a such library for ios.
You can have similar results (but not json as input) with Visual Format Language
https://developer.apple.com/library/content/documentation/UserExperience/Conceptual/AutolayoutPG/VisualFormatLanguage.html
