### ISSUE TITLE
Implement support for output of generated json to a file

### ISSUE THREAD

**Issue by ndegwamartin** [Avocarrot/json2view#44]

**Comment by tsiougkosn** [comment]
hey @ndegwamartin, what json do you want as output ?
The json2view gets an json input, translate and create it to android views and the output is a View

**Comment by ndegwamartin** [comment]
@tsiougkosn hey, sorry I wasn't clear on my requirement, what I wanted was the ability to output the groovy generated json to a file instead of just stdout.

I forked the project and made the update here https://github.com/ndegwamartin/json2view

Now if you run the script with this 
<code> ./gradlew runScript -Pxml=./pathToInputXmlFile.xml -Poutput=file</code> 
it outputs the json to a file <code>(pathToInputXmlFile.json)</code>
