### ISSUE TITLE
Configuration on demand is not supported

### ISSUE THREAD

**Issue by mgood7123** [Avocarrot/json2view#52]
Configuration on demand is not supported by the current version of the Android Gradle plugin since you are using Gradle version 4.6 or above. Suggestion: disable configuration on demand by setting org.gradle.configureondemand=false in your gradle.properties file or use a Gradle version less than 4.6.

**Comment by pavlospt** [comment]
The project does not contain that flag in its `gradle.properties`. Please check the equivalent flag in your Android Studio!

**Comment by mgood7123** [comment]
> The project does not contain that flag in its `gradle.properties`. Please check the equivalent flag in your Android Studio!

it builds if i keep the gradel version as 3.3.2
